name: Deploy Files to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download ngrok
        run: |
          mkdir -p build/files
          wget -O build/files/ngrok-v3-stable-linux-amd64.tgz https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz

      - name: Create HTML file
        run: |
          mkdir -p build
          cat <<EOF > build/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Download Files</title>
</head>
<body>
    <h1>Download Files</h1>
    <ul>
        <li><a href="files/ngrok-v3-stable-linux-amd64.tgz" download>Download ngrok-v3-stable-linux-amd64.tgz</a></li>
        <!-- Add more links here if you have more files -->
    </ul>
</body>
</html>
EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}  # Replace with the correct secret name
          publish_dir: ./build
