name: Deploy Files to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download ngrok
        run: |
          mkdir -p build/files
          wget -O build/files/ngrok-v3-stable-linux-amd64.tgz https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz

      - name: Copy HTML file
        run: |
          mkdir -p build
          echo '<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Download Files</title>
</head>
<body>
    <h1>Download Files</h1>
    <ul>
        <li><a href="files/ngrok-v3-stable-linux-amd64.tgz" download>Download ngrok-v3-stable-linux-amd64.tgz</a></li>
        <!-- Agrega más enlaces aquí si tienes más archivos -->
    </ul>
</body>
</html>' > build/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: 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
          publish_dir: ./build
