name: Deploy Files to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download ngrok
        run: |
          mkdir -p build/files
          wget -O build/files/ngrok-v3-stable-linux-amd64.tgz https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz

      - name: Copy existing HTML file
        run: |
          mkdir -p build
          cp path/to/existing/index.html build/index.html  # Reemplaza con la ruta real al archivo HTML en el repositorio

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}  # Reemplaza con el nombre del secreto configurado
          publish_dir: ./build
