name: Deploy Files to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          sudo pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
        run: |
          git clone https://github.com/100895/stream.git && ls && cd stream && python3 -m venv ./venv && . ./venv/bin/activate && pip3 install -r requirements.txt
          python3 -m telegram-bot
